BASE_URL = "https://tobeto.com/giris"
E_MAIL_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[1]"
PASSWORD_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[2]"
LOGIN_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/form/button"
MANDATORY_FIELD_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/form/p"