BASE_URL = "https://tobeto.com/giris"
E_MAIL_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[1]"
PASSWORD_XPATH = "/html/body/div[1]/div/main/section/div/div/div/div/form/input[2]"
LOGIN_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/form/button"
MANDATORY_FIELD_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/form/p"
LOGIN_PAGE_TOBETO_IMG = "//*[@id='__next']/div/main/section/div/div/div/div/div[1]/span/img"
FORGOT_PASSWORD = "//*[@id='__next']/div/main/section/div/div/div/div/form/label/small/p"
SIGN_UP_TEXT = "//*[@id='__next']/div/main/section/div/div/div/div/div[2]/label/small"
SYSTEM_MESSAGE = "//*[@id='__next']/div/main/div[2]/div/div[2]"
MY_PROFIL_XPATH = "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
MY_PROFIL_CONTENT_XPATH = "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
SIGN_UP_BUTTON = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div[2]/label/small/a"
SIGN_UP_NAME = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[1]"
SIGN_UP_SURNAME = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[2]"
SIGN_UP_EMAIL = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[3]"
SIGN_UP_PASSWORD = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[4]"
SIGN_UP_PASSWORD_AGAIN = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[5]"
SIGN_UP_CONTINUE = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
SIGN_UP_CONTRACT = "/html/body/div[4]/div/div/div/div/div/p"
SIGN_UP_CHECKBOX_1= "/html/body/div[4]/div/div/div/div/div/label[2]/small/input"
SIGN_UP_CHECKBOX_2= "/html/body/div[4]/div/div/div/div/div/label[3]/small/input"
SIGN_UP_CHECKBOX_3= "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[1]/input"
SIGN_UP_CHECKBOX_4= "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[2]/input"
SIGN_UP_PHONE= "//*[@id='phoneNumber']"
SIGN_UP_CAPTCHA= "//*[@id='recaptcha-anchor']"
SIGN_UP_FINISH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"


